services:
  redbetter:
    image: redbetter:local
    container_name: redbetter
    restart: unless-stopped
    volumes:
      - /Volumes/Downloads:/downloads
      - /Users/matthew/PycharmProjects/redbetter/docker:/config
      - /Users/matthew/PycharmProjects/redbetter/transcodes:/transcodes
    environment:
      TZ: 'Asia/Seoul'
      PYTHONPATH: /app
      CONFIG_FILE_PATH: /config/config.ini
    ports:
      - '9725:9725'
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "9725"]
