services:
  redbetter:
    image: bofalot/redbetter:latest
    container_name: redbetter
    restart: unless-stopped
    volumes:
      - /mnt/user/Downloads:/downloads
      - /mnt/user/appdata/redbetter:/config
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - '9725:9725'
    command:
      - /app/main.py
      - --config
      - /config/config.ini
      - --cache
      - /config/cache

