services:
  redbetter:
    image: redbetter:local
    container_name: redbetter
    restart: unless-stopped
    volumes:
      - /Volumes/Downloads:/downloads
      - /Users/matthew/PycharmProjects/redbetter/docker:/config
      - /Users/matthew/PycharmProjects/redbetter/transcodes:/transcodes
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - '9725:9725'
    command:
      - /app/redbetter/main.py
      - --config
      - /config/config.ini
      - --cache
      - /config/cache
